session: SessionInterface
cache: CacheInterface
cookie: CookieInterface
request: RequestHandler
response: ResponseHandler
token: Token
money: MoneyManager
# queryParams: QueryParamsInterface
helper: ModelHelper
# repository: RepositoryFactory
validator: Validator
factory: ModelFactory
