session: SessionInterface
cache: CacheInterface
cookie: CookieInterface
request: RequestHandler
response: ResponseHandler
token: Token
helper: ControllerHelper
dispatcher: DispatcherFactory
# comment: CommentsFactory
